#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# ============================================================
#  cookie_extract：读取浏览器登录态 cookie → cookies.txt（Netscape 格式）
#
#  用途：抖音/小红书等需要登录态的下载（yt-dlp --cookies 文件）
#  原理：浏览器 cookie 存 SQLite（AES-256-GCM 加密，v10），
#        解密密钥在 macOS 钥匙串「Chrome Safe Storage」——本地解密，零云
#
#  用法：
#    python3 cookie_extract.py douyin --browser chrome --out cookies.txt
#    python3 cookie_extract.py "douyin.com" "xiaohongshu.com" -o /tmp/cookies.txt
# ============================================================
import argparse, hashlib, json, os, shutil, sqlite3, subprocess, sys, tempfile
from pathlib import Path
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives import hashes

# 各浏览器 cookie 库路径（macOS）
BROWSER_DBS = {
    "chrome": "~/Library/Application Support/Google/Chrome",
    "edge": "~/Library/Application Support/Microsoft Edge",
    "brave": "~/Library/Application Support/BraveSoftware/Brave-Browser",
    "arc": "~/Library/Application Support/Arc/User Data",
    "vivaldi": "~/Library/Application Support/Vivaldi",
    "chromium": "~/Library/Application Support/Chromium",
    "opera": "~/Library/Application Support/com.operasoftware.Opera",
}

# 各浏览器钥匙串密钥条目名
KEYCHAIN_SERVICE = {
    "chrome": "Chrome Safe Storage",
    "edge": "Microsoft Edge Safe Storage",
    "brave": "Brave Safe Storage",
    "arc": "Arc Safe Storage",
    "vivaldi": "Vivaldi Safe Storage",
    "chromium": "Chromium Safe Storage",
    "opera": "Opera Safe Storage",
}


def get_keychain_key(service):
    """读 macOS 钥匙串里的浏览器加密主密码（首次会弹系统授权）"""
    r = subprocess.run(["security", "find-generic-password", "-w", "-s", service],
                       capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError(f"读取钥匙串失败（{service}）：{r.stderr.strip()[:120]}"
                           "\n请在弹窗中点「允许」，或在系统设置→隐私与安全性→钥匙串中授权")
    return r.stdout.strip().encode("utf-8")


def derive_key(password):
    """macOS v10 密钥派生：PBKDF2-HMAC-SHA1(saltysalt, 1003) → 16 字节 AES-128 key"""
    return PBKDF2HMAC(hashes.SHA1(), 16, b"saltysalt", 1003).derive(password)


def decrypt_value(encrypted, key, host_key=""):
    """解密 Chrome v10 cookie value（macOS：AES-128-CBC + v10 前缀 + 32B host 哈希前缀）
    Chrome 127+ 明文前 32 字节 = SHA-256(host_key)，需剥离"""
    if not encrypted:
        return ""
    if not encrypted.startswith(b"v10"):
        return encrypted.decode("utf-8", "ignore")
    cipher = Cipher(algorithms.AES(key), modes.CBC(b" " * 16))
    plain = cipher.decryptor().update(encrypted[3:]) + cipher.decryptor().finalize()
    # 去 PKCS7 填充
    pad = plain[-1]
    if 1 <= pad <= 16:
        plain = plain[:-pad]
    # 去 Chrome 127+ 的 host 哈希前缀（32 字节 = SHA-256(host_key)）
    if len(plain) >= 32 and hashlib.sha256(host_key.encode()).digest() == plain[:32]:
        plain = plain[32:]
    return plain.decode("utf-8", "ignore")


def extract_cookies(domain_keywords, browser="chrome", out=None):
    """提取指定域名 cookie → cookies.txt，返回输出路径"""
    base = Path(os.path.expanduser(BROWSER_DBS[browser]))
    db = base / "Default" / "Network" / "Cookies"          # Chrome 89+
    if not db.is_file():
        db = base / "Default" / "Cookies"                  # 旧版路径
    if not db.is_file():
        raise RuntimeError(f"未找到 {browser} 的 cookie 数据库：{db}")

    key = derive_key(get_keychain_key(KEYCHAIN_SERVICE[browser]))

    # 只读直连原始库（WAL 模式支持并发只读，SQLite 自动合并 WAL，拿到最新一致数据）
    conn = sqlite3.connect(f"file:{db}?mode=ro", uri=True)
    rows = conn.execute(
        "SELECT host_key, path, is_secure, expires_utc, name, encrypted_value, is_httponly "
        "FROM cookies WHERE " + " OR ".join("host_key LIKE ?" for _ in domain_keywords),
        [f"%{k}%" for k in domain_keywords]).fetchall()
    conn.close()
    if not rows:
        raise RuntimeError(f"未找到 {domain_keywords} 的 cookie（请确认已在 {browser} 登录对应网站）")

    out_path = Path(out) if out else Path(tempfile.gettempdir()) / f"{browser}_cookies.txt"
    lines = ["# Netscape HTTP Cookie File", "# Generated by cookie_extract.py (local)"]
    for host, path, secure, expires, name, enc, httponly in rows:
        value = decrypt_value(bytes(enc), key, host)
        if not value:
            continue
        exp = str(max(1, int(expires) // 1000000)) if expires and expires > 0 else "0"
        domain = host if host.startswith(".") else f".{host}"
        lines.append("\t".join([domain, "TRUE", path or "/",
                                "TRUE" if secure else "FALSE", exp, name, value]))
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"✅ 已提取 {len(rows)} 条 cookie（{domain_keywords}）→ {out_path}")
    return out_path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("domains", nargs="+", help="域名关键字（如 douyin / xiaohongshu）")
    ap.add_argument("--browser", default="chrome", choices=list(BROWSER_DBS.keys()))
    ap.add_argument("-o", "--out", help="输出 cookies.txt 路径（默认 /tmp/{browser}_cookies.txt）")
    args = ap.parse_args()
    try:
        extract_cookies(args.domains, args.browser, args.out)
    except RuntimeError as e:
        print(f"✗ {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
